### ISSUE TITLE
Communications Verbiage for Pickup/Dropoff Tasks

### ISSUE THREAD

**Issue by JemWritesCode** [Jemmeh/GetUsPPELogistics#2]
We can send messages at various points during the OnFleet delivery to communicate with donors and hospitals. These messages need to be written. They can be set from the admin settings within OnFleet.

Pickups -- usually donors
Dropoffs -- usually healthcare facilities or holding areas (someone's house, a supplies hub, etc)

**For:** 
Pickup & Dropoff Tasks
Pickup Tasks Only
Dropoff Tasks Only

**Trigger Times:**
Task Started
Task Completed
Driver Arriving
ETA is ...
Task Failed
Dependency Started
Dependency Completed
Predicted ETA is...

**Tags** -- Personalization variables, these tags will be replaced with the relevant info.
{recipientName} 
{workerName} 
{eta} 
{eta}
 {vehicleDescription}
 {vehicleType} 
{vehicleLicensePlate}
 {workerPhone} 
{taskShortId}
 {destinationAddressShort}
 {destinationAddressLong} 
{trakLink} 
{creatorName}

**Comment by JemWritesCode** [comment]
Task Started will most likely need to say something to the tune of 

Pickups: "A driver has become available to pick up your PPE supplies and is on the way! If you are no longer available, please text us immediately so we can reschedule. Thanks!"

Dropoffs: "A driver is on the way to drop off some PPE supplies! Please text us immediately if you cannot take these right now so we can reschedule. Thanks!"

**Comment by JemWritesCode** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OnFleet - Routes, Driver/Donor Communication, Dropoff Pictures](https://trello.com/c/8AOdGuwj/2-onfleet-routes-driver-donor-communication-dropoff-pictures)

**Comment by JemWritesCode** [comment]
Some of this has been written, it's stored in the OnFleet admin settings.

**Comment by murthykk** [comment]
I believe this is fixed. I’ve been tweaking the writing since the day before the OnFleet switchover, and I think it’s pretty solid now. Feel free to re-open if you feel otherwise.
